export const REDIS_CONNECT_DATABASE  = 'REDIS_CONNECT_DATABASE';
export const REDIS_UPDATE_DATA       = 'REDIS_UPDATE_DATA';
export const REDIS_FETCH_ALL         = 'REDIS_FETCH_ALL';
export const REDIS_SELECT_SERVER     = 'REDIS_SELECT_SERVER';
export const REDIS_ADD_SERVER        = 'REDIS_ADD_SERVER';
export const REDIS_UPDATE_KEY        = 'REDIS_UPDATE_KEY';
export const REDIS_REMOVE_SERVER     = 'REDIS_REMOVE_SERVER';
export const REDIS_DISCONECT_SERVER  = 'REDIS_DISCONECT_SERVER';

export const HOSTS_INITIALIZE        = 'HOSTS_INITIALIZE';
export const HOSTS_CLEAR_HOSTS       = 'HOSTS_CLEAR_HOSTS';
export const HOSTS_ADD_HOST          = 'HOSTS_ADD_HOST';
export const HOSTS_UPDATE_HOST       = 'HOSTS_UPDATE_HOST';
export const HOSTS_REMOVE_HOST       = 'HOSTS_REMOVE_HOST';
export const HOSTS_SAVE_STORAGE      = 'HOSTS_SAVE_STORAGE';
